### ISSUE TITLE
Any updates to this?

### ISSUE THREAD

**Issue by Jonovono** [kanaka/clojurescript#35]
Hi. This project looks neat, but looks like it has gone stagnant. How come development has stopped? Are there any new projects adressing the goals of this?

I am having trouble getting this to work.

I cloned it as is. 

When run the first command: ../bin/cljsc ../src/cljs/webrepl.cljs > webrepl.js

I get: Error: Could not find or load main class clojure.main

**Comment by Hendekagon** [comment]
./script/bootstrap

**Comment by Jonovono** [comment]
Cool, thanks!

Can you comment on what the current status of the project is?

**Comment by kanaka** [comment]
It's dormant but not dead. I've recently started grad school and my company was purchased so I haven't had much chance lately to work with this. My biggest goal was to get normal ClojureScript code compiling without needing Clojure and that's basically been completed (see clojurescript.net). Really, the big remaining tasks are:
- Get the compiler to be self-hosting so the JS build can recompile the whole of cljs-in-cljs. Compiling core.clj/core.cljs doesn't work yet. @arthuredelstein might be working on pushing this part forward (https://github.com/kanaka/clojurescript/issues/22)
- More work and design around ns/require/use
- Clean up and refactor all the changes into standalone units that can be pushed back upstream into ClojureScript proper. These will probably need to be accompanied by performance tests to show that the changes don't have a negative impact on standard ClojureScript compiled with Clojure. It also hasn't been merged with ClojureScript upstream in a while so that will need to happen too.
